name: build-deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup python-3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: setup node-12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install dependencies
        shell: bash
        run: |
          sudo apt-get install -y jq
          python -m pip install --upgrade pip
          make requirements npm-install

      - name: build products service
        shell: bash
        run: |
          make build-products
          sleep 5



      - name: deploy products service
        shell: bash
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          make deploy-products

      - uses: actions/upload-artifact@v3
        with:
          name: products-svc-artifact
          path: products/build
      

